name: SQLiteo
options:
  bundleIdPrefix: com.adamghill

packages:
  CodeEditor:
    url: https://github.com/ZeeZide/CodeEditor.git
    from: 1.0.0
  GRDB.swift:
    url: https://github.com/groue/GRDB.swift.git
    from: 6.29.3

targets:
  SQLiteo:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/SQLiteo
      - path: Sources/SQLiteo/Assets.xcassets
        buildPhase: resources
    info:
      path: Sources/SQLiteo/Info.plist
    settings:
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_ENTITLEMENTS: Sources/SQLiteo/SQLiteo.entitlements
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      CODE_SIGN_IDENTITY: "-"
      CODE_SIGN_STYLE: Manual
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: CodeEditor
      - package: GRDB.swift
        product: GRDB
